# -*- coding: utf-8 -*-
"""PartC_Inference_Instruction_vLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERIw-vmeFdXMXf0YWAghv7eRhHCcL3HK

# <font color = 'indianred'>**Multilabel Classification of StackExchange Dataset using GEMMA** </font>

**Objective:**<br>
Demonstrate inference and evaluation of an Instruction Gemma-2-2B-it model for a multilabel text classification task on the StackExchange dataset using vLLM.
The notebook shows how to: <br>

1. Perform guided (constrained) decoding via JSON schema enforcement to produce structured label outputs.<br>
2. Generate predictions with vLLM’s high-performance inference engine.<br>
3. Evaluate results using multilabel metrics (macro F1) and visualize performance through confusion matrices.<br>
4. Log validation and test performance to Weights & Biases (WandB) for experiment tracking.<br>

**Plan**

1. Set Environment
2. Load Dataset
3. Download Model and setup vLLM
4. Setup WandB
5. Validation
6. Performance on Test Set

# <font color = 'indianred'> **1. Setting up the Environment** </font>
"""

if 'google.colab' in str(get_ipython()):
    !pip install numpy -U -qq
    !pip install transformers evaluate wandb datasets accelerate trl peft bitsandbytes -U -qq
    !pip install vllm==0.11.2
    !pip uninstall tensorflow -y -qq

"""<Font size = 5 color = 'indianred'>**Restart the session before moving onto next cell**
> Runtime- Restart Session

<font color = 'indianred'> *Load Libraries* </font>
"""

import os
os.environ['VLLM_USE_V1'] = '1' # this should be done befre any other import

import torch
import torch.nn as nn
from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest
from vllm.sampling_params import GuidedDecodingParams

# standard pythgion libraries
from pathlib import Path

from typing import Dict, List, Union, Optional, Tuple
from tqdm import tqdm
import json
import os
import sys

# Data Science librraies
import numpy as np
import pandas as pd

from pprint import pprint

# Pytorch
import torch

# Huggingface Librraies
import evaluate
from datasets import load_dataset

from huggingface_hub import login

# Logging and secrets
import wandb
from google.colab import userdata
from huggingface_hub import login, HfApi, create_repo

# standard pythgion libraries
from pathlib import Path

from typing import Dict, List, Union, Optional, Tuple
from tqdm import tqdm
import json
import os
import sys

# Data Science librraies
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from pprint import pprint

# Pytorch
import torch

# Huggingface Librraies
import evaluate
from datasets import load_dataset

from huggingface_hub import login

# Logging and secrets
import wandb
from google.colab import userdata
from huggingface_hub import login, HfApi, create_repo

sys.path

# If running on Google Colab, use Google Drive as storage
# CHANGE FOLDERS TO WHERE YOU WANT TO SAVE DATA AND MODELS

if 'google.colab' in str(get_ipython()):
    from google.colab import drive  # Import Google Drive mounting utility
    drive.mount('/content/drive')  # Mount Google Drive

    # Set base folder path for storing data on Google Drive
    data_folder= Path('/content/drive/MyDrive')
    project_folder = Path('/content/drive/MyDrive')
    base_folder = Path('/content/drive/MyDrive')

# If running locally, specify a different path
else:
    # Set base folder path for storing data on local machine
    data_folder= Path('/home/harpreet/Insync/google_drive_shaannoor/data')
    project_folder= Path('/home/harpreet/Insync/google_drive_shaannoor/teaching_fall_2025/LLM_Fall_2025/')

util_folder = project_folder/'shared_utils'

sys.path.append(str(util_folder))

sys.path

from shared_utils import free_gpu_memory,  multilabel_evaluation

wandb_api_key = userdata.get('WANDB_API_KEY')
hf_token = userdata.get('HF_TOKEN')

if hf_token:
    # Log in to Hugging Face
    login(token=hf_token)
    print("Successfully logged in to Hugging Face!")
else:
    print("Hugging Face token not found in notebook secrets.")

if wandb_api_key:
  wandb.login(key=wandb_api_key)
  print("Successfully logged in to WANDB!")
else:
    print("WANDB key not found in notebook secrets.")

kaggle_api = base_folder/'.kaggle'
import os
if 'google.colab' in str(get_ipython()):
    os.environ['KAGGLE_CONFIG_DIR'] = "/content/drive/MyDrive/ADL_MSBA_UTD/.kaggle/"
if 'google.colab' in str(get_ipython()):
    !chmod 600 /content/drive/MyDrive/.kaggle/kaggle.json
if 'google.colab' in str(get_ipython()):
    ! ls -la  /content/drive/MyDrive/.kaggle/kaggle.json

"""# <font color = 'indianred'> **2. Load Data set**
    

"""

val_split = load_dataset('sayedyounes/stack_multilabel_subset_chat', split = 'valid')
test_split = load_dataset('sayedyounes/stack_multilabel_subset_chat', split = 'test')
print()
print(val_split[0])

"""#  <font color = 'indianred'> **3. Download Model and setup vLLM**"""

torch.cuda.empty_cache()
BASE_MODEL = "google/gemma-2-2b-it"
LORA_ADAPTER = "sayedyounes/stack_exc_multilabel_instr_lm_head"

llm = LLM(
    model=BASE_MODEL,
    dtype=torch.bfloat16,
    trust_remote_code=True,
    quantization="bitsandbytes",
    enable_lora=True,
    max_lora_rank=128,
    gpu_memory_utilization=0.8,
    guided_decoding_backend="outlines",
)

lora_request = LoRARequest(
    lora_name="stack_classifier",
    lora_int_id=1,
    lora_path=LORA_ADAPTER
)

class_names = ['anger', 'anticipation', 'disgust', 'fear', 'joy',
               'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

array_schema = {
    "type": "array",
    "items": {
        "type": "string",
        "enum": class_names
    },
    "minItems": 0,
    "maxItems": 11
}

guided_decoding = GuidedDecodingParams(
    json=array_schema,
    backend="outlines"
)

sampling_params = SamplingParams(
    temperature=0,
    max_tokens=100,
    guided_decoding=guided_decoding,
)

"""# <font color = 'indianred'> **4. Setup WandB**</font>"""

# Commented out IPython magic to ensure Python compatibility.

# %env WANDB_PROJECT = emotion-detection

run = wandb.init(

    project="emotion-detection",
    #entity="mxg230038-the-university-of-texas-at-dallas",
    name="partC_inference_instruction_vllm",
    tags=["part-c", "inference", "instruction", "vllm"],
)

"""#<font color = 'indianred'> **5. Utility Functions**"""

def generate_predictions_batch(prompts: List[str],
                               llm: LLM,
                               sampling_params: SamplingParams,
                               lora_request: LoRARequest,
                               batch_size: int = 64) -> List[List[str]]:
    """
    Generate predictions for a list of prompts using vLLM batch inference.

    Args:
        prompts: List of input prompts
        llm: vLLM model instance
        sampling_params: Sampling parameters for generation
        lora_request: LoRA adapter request
        batch_size: Batch size for inference

    Returns:
        List of predicted labels (as lists of strings)
    """
    predictions = []

    for i in tqdm(range(0, len(prompts), batch_size), desc="Generating predictions"):
        batch = prompts[i:i+batch_size]

        outputs = llm.generate(
            batch,
            sampling_params,
            lora_request=lora_request
        )

        for output in outputs:
            pred = json.loads(output.outputs[0].text)
            predictions.append(pred)


    print(f"Processed {len(predictions)}/{len(prompts)} prompts")
    return predictions

def parse_label_string(label_str: str) -> List[str]:
    """Parse label string to list of labels."""
    try:
        return json.loads(label_str.strip())
    except:
        return []

f1 = evaluate.load('f1','multilabel')
def compute_metrics( labels, preds):
  f1_macro = f1.compute(predictions=preds, references=labels, average='macro')
  return {'f1_macro':f1_macro['f1'],}

def evaluate_multilabel_predictions(true_labels: Union[List[str], List[List[str]]],
                                     predictions: List[List[str]],
                                     class_names: List[str],
                                     split_name: str = "valid",
                                     log_to_wandb: bool = True,
                                     show_confusion_matrix: bool = True) -> Dict:
    """
    Evaluate multilabel predictions and optionally log to wandb.

    Args:
        true_labels: List of label strings OR list of label lists
        predictions: List of predicted label lists
        class_names: List of all possible class names
        split_name: Name of the split (for wandb logging)
        log_to_wandb: Whether to log metrics to wandb
        show_confusion_matrix: Whether to display confusion matrix

    Returns:
        Dictionary containing evaluation metrics
    """
    # Parse true labels only if they are strings
    if len(true_labels) > 0 and isinstance(true_labels[0], str):
        parsed_labels = [parse_label_string(label) for label in true_labels]
        print(f"Parsed string labels to lists")
    else:
        parsed_labels = true_labels
        print(f"Labels already in list format")

    # Initialize MultiLabelBinarizer
    mlb = MultiLabelBinarizer(classes=class_names)
    mlb.fit([class_names])  # Fit with all possible classes

    # Transform to binary format
    labels_binary = mlb.transform(parsed_labels)
    predictions_binary = mlb.transform(predictions)

    # Print samples and shapes
    print(f"\n{'='*60}")
    print(f"{split_name.upper()} SET EVALUATION")
    print(f"{'='*60}")
    print(f"Sample true labels: {parsed_labels[:3]}")
    print(f"Sample predictions: {predictions[:3]}")
    print(f"\nBinary shapes:")
    print(f"  Labels:      {labels_binary.shape}")
    print(f"  Predictions: {predictions_binary.shape}")

    # Compute metrics
    metrics = compute_metrics(labels_binary, predictions_binary)
    print(f"\nMetrics:")
    print(f"  F1 Macro: {metrics['f1_macro']:.4f}")

    # Log to wandb
    if log_to_wandb:
        wandb.log({f"{split_name}_f1_macro": metrics["f1_macro"]})
        print(f"  ✓ Logged to wandb")

    # Display confusion matrix
    if show_confusion_matrix:
        print(f"\nConfusion Matrix:")
        multilabel_evaluation(
            y_true=labels_binary,
            y_pred=predictions_binary,
            class_names=class_names,
            figsize=(12, 8)
        )

    return metrics

"""#<font color = 'indianred'> **6. Performance on Validation Set**

<font color = 'indianred'> *Evaluate model on Validation Set* </font>

"""

class_names

tokenizer = llm.get_tokenizer()

tokenizer.chat_template

# Save template to file
with open('template.jinja', 'w') as f:
    f.write(tokenizer.chat_template)
# Format it
!djlint template.jinja --reformat --quiet
# Read it back
with open('template.jinja', 'r') as f:
    print(f.read())

val_prompts = [
    tokenizer.apply_chat_template(
        [{"role": "user", "content": example["messages"][0]["content"]}],
        tokenize=False,
        add_generation_prompt=True
    )
    for example in val_split
]

print(val_prompts[0])

val_predictions = generate_predictions_batch(
    prompts=val_prompts,
    llm=llm,
    sampling_params=sampling_params,
    lora_request=lora_request,
    batch_size=64
)

val_predictions[0:5]

# Extract ground truth labels
val_labels = [
    json.loads(example["messages"][1]["content"])  # Assistant's message
    for example in val_split
]

val_labels[0:5]

# Evaluate
valid_metrics = evaluate_multilabel_predictions(
    true_labels=val_labels,
    predictions=val_predictions,
    class_names=class_names,
    split_name="valid",
    log_to_wandb=True,
    show_confusion_matrix=True
)

"""#  <font color = 'indianred'> **7. Performance on Test Set** </font>
For test set evaluation, we will perfrom following steps:
"""

test_prompts = [
    tokenizer.apply_chat_template(
        [{"role": "user", "content": example["messages"][0]["content"]}],
        tokenize=False,
        add_generation_prompt=True
    )
    for example in test_split
]

# Generate predictions
test_predictions = generate_predictions_batch(
    prompts=test_prompts,
    llm=llm,
    sampling_params=sampling_params,
    lora_request=lora_request,
    batch_size=128
)

# Extract ground truth labels
test_labels = [
    json.loads(example["messages"][1]["content"])
    for example in test_split
]

test_labels[0:5]

# Evaluate
test_metrics = evaluate_multilabel_predictions(
    true_labels=test_labels,
    predictions=test_predictions,
    class_names=class_names,
    split_name="test",
    log_to_wandb=True,
    show_confusion_matrix=True
)

wandb.finish()



"""# <font color = 'indianred'> **8. Inference** </font>

<font color = 'indianred'> *Demonstrate inference on a single text input* </font>

"""

def create_chat_prompt_for_single_text(text: str, tokenizer) -> str:
    user_message = f"""Classify the TEXT by selecting all applicable labels from the following list: {class_names}.

TEXT: {text}"""


    # Format as chat message
    messages = [{"role": "user", "content": user_message}]

    # Apply chat template
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    return prompt

"""## <font color = 'indianred'> Example 1: Single text *inference* </font>

"""

#Example 1: Single text inference
text_1 = "I am so excited and happy about the new project! Can't wait to get started!"

# Create chat-formatted prompt
prompt_1 = create_chat_prompt_for_single_text(text_1, tokenizer)

# Predict using existing function (pass as single-item list)
prediction_1 = generate_predictions_batch(
    prompts=[prompt_1],  # Single prompt as a list
    llm=llm,
    sampling_params=sampling_params,
    lora_request=lora_request,
    batch_size=1
)

print("\nInput Text:")
pprint(text_1)
print("\n" + "="*60)
print("Formatted prompt:")
pprint(prompt_1)
print("\n" + "="*60)
print(f"Predicted Labels: {prediction_1[0]}")  # Get first (only) prediction

"""## <font color = 'indianred'> Example 2: Multiple custom texts at once </font>

"""

#Example 2: Multiple custom texts at once
custom_texts = [
    "I'm feeling really anxious about the exam tomorrow",
    "What a beautiful day! Everything is going perfectly!",
    "I can't believe they did that. I'm so angry right now.",
    "Worried about the future but trying to stay optimistic"
]
# Create chat-formatted prompts
custom_prompts = [create_chat_prompt_for_single_text(text, tokenizer) for text in custom_texts]

# Predict using existing function
custom_predictions = generate_predictions_batch(
    prompts=custom_prompts,
    llm=llm,
    sampling_params=sampling_params,
    lora_request=lora_request,
    batch_size=64
)

# Display results
print("Batch Inference Results:")
print("="*60)
for text, pred in zip(custom_texts, custom_predictions):
    print(f"\nText: {text}")
    print(f"Predicted Labels: {pred}")
    print("-"*60)

